# Generated by Django 2.0.2 on 2018-06-10 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='hunter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='votes_total',
            field=models.IntegerField(default=1),
        ),
    ]
